export const FETCH_API_ORDER_BOOK = "FETCH_API_ORDER_BOOK";
export const FETCH_API_ORDER_BOOK_SUCCESS = "FETCH_API_ORDER_BOOK_SUCCESS";
export const FETCH_API_ORDER_BOOK_ERR = "FETCH_API_ORDER_BOOK_ERR";

export const DELETE_API_ORDER_BOOK = "DELETE_API_ORDER_BOOK";
export const DELETE_API_ORDER_BOOK_SUCCESS = "DELETE_API_ORDER_BOOK_SUCCESS";
export const DELETE_API_ORDER_BOOK_ERR = "DELETE_API_ORDER_BOOK_ERR";
