export const FETCH_API_ASSET_TOP_PLAYER = "FETCH_API_ASSET_TOP_PLAYER";
export const FETCH_API_ASSET_TOP_PLAYER_SUCCESS =
  "FETCH_API_ASSET_TOP_PLAYER_SUCCESS";
export const FETCH_API_ASSET_TOP_PLAYER_ERR = "FETCH_API_ASSET_TOP_PLAYER_ERR";
