export const FETCH_API_PRICE_BOTTOM = "FETCH_API_PRICE_BOTTOM";
export const FETCH_API_PRICE_BOTTOM_SUCCESS = "FETCH_API_PRICE_BOTTOM_SUCCESS";
export const FETCH_API_PRICE_BOTTOM_ERR = "FETCH_API_PRICE_BOTTOM_ERR";
